name: Deploy Site

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x

steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Cache node_modules
      uses: actions/cache@v1
      env:
        cache-name: hexo-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
  - name: Cache workers-site/node_modules
      uses: actions/cache@v1
      env:
        cache-name: workers-site-node-modules
      with:
        path: workers-site/node_modules
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('workers-site/package-lock.json') }}
  - name: NPM install
    run: npm install
  - name: First Script
    run: ${{ secrets.first }}
  - name: Bulid Blog
    run: |
        hexo clean
        hexo g
  - name: Commit report
    run: |
        cd ./public
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://${{ secrets.TOKEN }}@github.com/blackyau/blog" master:master
